IMSmobile/app

README.md
With TSLint in vscode one does not need to run gulp manually to see linter warnings.
=> add vscode tslint extension to project plan

.travis.yml
Quick workaround to unbreak CI build due to breaking changes in `ionic package` starting with ionic-cli v3.
Created #278 to update our CI to ionic-cli v3.
=> Pin ionic cli version in CI to pre v3 (unbreak CI)

.travis.yml, src/models/entries-point.ts, src/models/entry-point.ts, src/providers/ims-service.spec.ts, src/providers/ims-service.ts
Using `thisArg` from `Array.prototype.find()` to get a parameterized `find()`.
=> Refactor: Move logic from EntryPoint and EntriesPoint models to ImsService

.travis.yml
Fix wrongly pinned version, which broke ios packaging.
Improvement on #279
=> Pin ionic cli version in CI to v2

src/pages/login/login.html
This should provide the correct keyboard layout for the URL input and be more comfortable for inputting (usually) lowercase usernames.
Tested on Android (may depend on installed keyboard) and iOS (with Ionic View only)
=> Login Form: disable username autocapitalization and set type on url

src/providers/camera-service.ts
Using [`Object.assign`](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) to copy the generic `cameraOptions` to `pictureOptions` and `galleryOptions`.
Depending on PR #391 the version needs to be increased approprately.
=> store generic camera options in one place

config.xml, package.json, src/pages/login/login.ts
As there are only three fields and no special validation it should be obvious what is invalid.
Also we disabled the red underlinig of invalid forms anyway in 6b6f0a9.
On the upload page we need to keep the `markAllAsTouched()` as it needs to be obvious which (of the possibily many) fields are invalid when hitting the upload button and getting the toast.
The marking of all child controls as touched is still not available in Angular.
=> Login Page: remove markAsTouched

CONTRIBUTING.md, README.md, package.json, scripts/release.js
Automatic creation of changelog was not working because tag have been deleted after squash commit. The new described workflow allows release generation directly on master branch and shortens the release process.
This closes #429
=> build:  add automatic release creation with node script

e2e/page-objects/upload-page-object.ts, e2e/upload.e2e-spec.ts, src/pages/upload/upload.html, src/pages/upload/upload.spec.ts, src/pages/upload/upload.ts
User should not be allowed to enter wrong input for boolean field type. The application now shows a toggle instead of an input field for boolean field types.
Closes #338
=> feat(upload): show boolean toggle for boolean upload field type

docs/protocols/2017-06-30-presentation-sprint9-imagic_PICSystem.md
This protocol documents sprint 9 review with the stakeholder from PIC and Imagic.
This close #442
=> docs: add protocol from sprint review 9

e2e/page-objects/upload-page-object.ts, e2e/upload.e2e-spec.ts, src/pages/upload/upload.html
Usually a from can be submitted by hitting the enter key in a browser or by pressing the native keyboard submit button on a mobile devices.  This change fix that in the upload page the form can be submitted in a standard way.
Closes #413
=> fix(upload): allow image upload with enter key or native keyboard submit button

tslint.json
Lint rules help to keep the code consitent. This PR is part of #436 that allows adding team defined lint rules.
Task of #436
=> build: add lint rules

e2e/archive-selection.e2e-spec.ts, e2e/login.e2e-spec.ts, e2e/logout.e2e-spec.ts, e2e/page-objects/entries-page-object.ts, e2e/page-objects/login-page-object.ts, e2e/page-objects/setting-archive-page-object.ts, e2e/page-objects/setting-image-field-page-object.ts, e2e/page-objects/settings-page-object.ts, e2e/page-objects/upload-page-object.ts, e2e/settings.e2e-spec.ts, e2e/upload.e2e-spec.ts, package.json, src/mocks/providers/transfer-blob-mock.ts, src/mocks/providers/transfer-mock.ts, ts-lintconfig.json
To ensure code consistency also check e2e test files with linter configuration. This removes the ionic app script lint checks as the current version is slow and the stable version uses outdated tslint version.
Closes #416
=> build: add linter test to e2e files

tslint.json
At least `check-type` got lost when we switched from the ionic app lint rules to our own. This activates all whitespace lint options.
=> build: extend lint rule "whitespace"

e2e/helpers/helpers.ts, src/mocks/ims-backend-mock.ts, src/models/errors/ims-server-connection-error.ts, src/models/ims-file-upload-headers.ts, src/models/ims-headers.ts, tslint.json
Using a template as a workaround when concatenating two different types in ImsBackendMock.
=> build: add lint rule  "restrict-plus-operands" and "prefer-template"

src/mocks/drag-event-mock.ts, src/mocks/mocks.ts, src/models/drag-event-counter.ts, src/models/ims-headers.ts, src/pages/entries/entries.spec.ts, src/pages/entries/entries.ts, src/pages/login/login.ts, src/pages/upload/upload.spec.ts, src/pages/upload/upload.ts, src/providers/browser-fileupload-selector-service.ts, tslint.json
StorageMock.get() on a undefined key now needs to return null to match the behaviour of ionic storage.
=> build: add lint rule "strict-boolean-expressions"

CHANGELOG.md, scripts/release.js
The npm library standard-version references to the commit guidelines defined in standard-version. This project has it's own commit guidelines thus we should reference those.
This closes #448
=> build: link to definition of done for commit guide lines in changelog

docs/spec.md
As discussed with stakeholders in the sprint 9 review the FA7 requirement can be downgraded from must to should.
Closes #446
=> docs: change requirement fa7 in spec to should

package.json, src/app/app.component.spec.ts, src/components/ims-field-selection/ims-field-selection.spec.ts, src/pages/entries/entries.spec.ts, src/pages/login/login.spec.ts, src/pages/setting-archive/setting-archive.spec.ts, src/pages/setting-entries-fields/setting-entries-fields.spec.ts, src/pages/setting-image-fields/setting-image-fields.spec.ts, src/pages/settings/settings.spec.ts, src/pages/upload/upload.spec.ts, src/providers/alert-service.spec.ts, src/providers/auth-service.spec.ts, src/providers/browser-container-upload-service.spec.ts, src/providers/browser-fileupload-selector-service.spec.ts, src/providers/browser-setting-service.spec.ts, src/providers/camera-service.spec.ts, src/providers/container-upload-service.spec.ts, src/providers/drag-event-counter-service.spec.ts, src/providers/drag-event-service.spec.ts, src/providers/entries-service.spec.ts, src/providers/ims-error-handler.spec.ts, src/providers/ims-service.spec.ts, src/providers/loading-service.spec.ts, src/providers/model-service.spec.ts, src/providers/query-builder-service.spec.ts, src/providers/setting-service.spec.ts, src/providers/token-service.spec.ts, src/providers/upload-service.spec.ts
As stated in the Angular docs, WebPack developers need not call compileComponents because it inlines templates and css as part of the automated build process that precedes running the test.
https://angular.io/guide/testing#compilecomponents
Using async inside the beforeEach seems to be necessary as a workaround for a jasmine issue with browser disconnects in Travis and Windows, see https://github.com/jasmine/jasmine/issues/1327.
For cleaner code this removes the asyncs and pins jasmine to 2.5.2 in package.json.
=> test: remove compileComponents and async from all specs

config.xml, package.json
App store validation requires that these strings are not empty.
=> fix(app): add a reason for camera and photo library access on ios

src/pages/login/login.ts
While starting the app or after a logout, the loginpagename will not be showed on browser as title.
Closes #451
=> fix(login): add pagetitle to loginpage

src/pages/entries/entries.html, src/pages/entries/entries.scss
On a small screen a field with lot of content isn't fully displayed on the entires page. This fix allows to horizontal scroll inside the area of the entry field.
Closes #536
=> fix: allow horizontal scroll if entry field is not fully displayed

e2e/entries.e2e-spec.ts, e2e/page-objects/entries-page-object.ts, src/pages/entries/entries.html
The field name in the entries list needs a lot of space. This leads to a hiding of content in the entries page.
This feature removes the display of the field name and shows the field content only. 
Closes #519
=> feat(entries): display only field content in entries list

README.md
Correct the link to the framework decision and fix some typos.
=> docs: add link to framework decision in document index

src/pages/upload/upload.spec.ts, src/pages/upload/upload.ts
When a keyword field was added to the list of upload fields the selection of a keyword only started worked after reloading the whole app.
Re-subscribe to keyword selection events on each visit of the upload page to ensure the event callback is aware of changes in the form fields.
Closes #570
=> fix(upload): selection not working immediately after adding keyword field

docs/Frameworkentscheid.md
To better link the framework requirements to the evaluation this adds the ID to the evaluation table and notes that not all requirements could be evaluated with the prototype.
=> docs: add frameworkrequirement ids to framework decision

docs/Frameworkentscheid.md, docs/decisionlog.md, docs/projektplan.md, docs/sad.md
=> docs: use Ionic instead of Ionic 2 as framework name

README.md, docs/projektplan.md
Add links to the source of the agile manifesto and the original author of the assemby flow.
Also remove a rather meaningless sentence concerning the scrum team.
Part of #532
=> docs: quote agile manifesto and assembly flow
