IMSmobile/app

- docs/anforderungskatalog.md
As a guide to evalute the framework.
> Add requiremens list

- docs/decisionlog.md
Import our decisions from Google Docs.
Closes #10
> Create Decision Log

- docs/decisionlog.md
Should cover what we decided today
> add new decisions

- docs/frameworkanforderungen.md
This document now only covers requirements for the cross-platform framework.
Closes #35
> rename framework requirements file

- docs/frameworkanforderungen.md
> link framework requirements to spec requirements

- docs/glossary.md
- docs/spec.md
> Separate glossary into it's own file from spec

- docs/spec.md
I kept two duplicate lines in merge 9a307c8
> spec.md remove duplicate non func reqs

- docs/frameworkanforderungen.md
Need to discuss. Plus some requirements are missing in my view:
- FA16 Direktupload
- NF8 Zentralkonfig
Closes #67 
As far as I see these requirements are not relevant for the framework:
ID   | Name | Beschreibung | Priorität | Quelle      | Status
---- | ---- | ------------ | --------- | ----------- | ------
A3  | Bildformat | Der Client muss die Bildformate PNG und JPEG in das Imagic IMS speichern können. | | PIC Systems |
FA4  | Bildattribute | Der Client muss das Bild inkl. EXIF-Daten ins das Imagic IMS speichern können. | | PIC Systems |
FA6  | Fallauswahl | Der Client muss dem Benutzer die Möglichkeit bieten einen bestehenden Fall auszwählen | | PIC Systems |
FA7  | Fallerstellung | Der Client muss dem Benutzer die Möglichkeit bieten einen neuen Fall zu erstellen | | PIC Systems | …
> Update framework requirements based on spec reqs

- README.md
> Remove chapter Organisationsstruktur and Externe Schnittstellen

- README.md
- docs/glossary.md
> Projectplan add chapter infrastructure

- README.md
- docs/decisionlog.md
> Projectplan chapter on code reviews

- README.md
> Describe our tools for project planning

- README.md
This isn't to specificy as we need to describe how to write unit and end-to-end tests once we know exactly how this works with ionoc
This closes #82
> Add overview about testing. 

- docs/questions.md
> Add feedback from pic systems to questions.md

- docs/glossary.md
- docs/protocols/2017-03-28-requirements-picsystems.md
- docs/spec.md
> Update requirements from PIC System meeting and add protocol

- README.md
There are probably some more things we do that I missed...
Closes #78
> Add overview of quality measure to project plan

- README.md
> Add Kostenvorgabe

- README.md
plus order names according to decision
Closes #117
> project plan: describe auftraggeber

- docs/Frameworkentscheid.md
> Framwork Decision

- README.md
This closes #115 project plan: add short section on framework decision
> Add framework to projectplan

- docs/risikoanalyse.md
plus fix some typos and table overflow
> Bring risk analysis up to date with framework decision

- .gitignore
- .vscode/launch.json
- README.md
- package.json
> Add possiblitly to debug ionic application and document how to debug

- README.md
> Add publisher links for police and medicine archive

- README.md
- src/model/credential.ts
- src/model/info.ts
- src/providers/ims-service.spec.ts
- src/providers/ims-service.ts
> Describe and example to create a unit test for provider

- README.md
- gulpfile.js
- package.json
- tslint.json
> Code guidelines

- README.md
> Add section about Wireframes to project plan

- README.md
Removed not used roles and filter
Create roles for each group a persona and create the correct permissions
This closes #158
> Add descirption to personas / test accounts

- .travis.yml
> Execute gulp in travis ci

- config.xml
> fixed slash direction for Apple world

- gulpfile.js
> Emit error when running gulp task in ci

- CONTRIBUTING.md
> Add rules about todo and testing on ios and android

- e2e/login-page-object.ts
- e2e/logout.e2e-spec.ts
- e2e/settings.e2e-spec.ts
- src/app/app.module.ts
- src/mocks/providers/mock-auth-service.ts
- src/pages/home/home.ts
- src/pages/more-popover/more-popover.html
- src/pages/more-popover/more-popover.scss
- src/pages/more-popover/more-popover.spec.ts
- src/pages/more-popover/more-popover.ts
- src/pages/popover/popover.html
- src/pages/popover/popover.scss
- src/pages/popover/popover.spec.ts
- src/pages/popover/popover.ts
- src/providers/auth-service.spec.ts
- src/providers/auth-service.ts
In comparison to PR #228 this version uses Auth Service.
E2E Test is still missing.
Closes #161
> Logout Button v2: Auth Service

- docs/spec.md
This does not specially mark which requirements are configurable, you still need to look out for "eingestellt werden". As the feedback from the Review is covered I think this is good enough to close #182 .
> Configurable reqs

- .gitignore
- .travis.yml
- README.md
- config.xml
- ionic.config.json
- package.json
- scripts/run-ionic-cloud-builds-on-pr-or-master.sh
- src/app/app.module.ts
Based on work in brach `ionic-Cloud`.
Closes #206
> CI build Android and iOS with Ionic Package

- src/mocks/mocks.ts
- src/pages/home/home.spec.ts
- src/pages/home/home.ts
- src/pages/more-popover/more-popover.spec.ts
- src/pages/more-popover/more-popover.ts
This closes #230 
Thanks to comment from @timvandijck on  https://github.com/driftyco/ionic/issues/8151 thread.
> Fix ios toolbar issue with using events.

- docs/spec.md
> Add reqs on fall modification and language

- src/mocks/mock-ims-backend.ts
- src/mocks/response/model-archives-point-response.ts
- src/mocks/response/model-fields-point-response.ts
- src/mocks/response/model-tables-point-response.ts
- src/models/metadata-field.ts
- src/models/metadata-table-fields.ts
- src/models/model-archives.ts
- src/models/model-link.ts
- src/models/model-tables.ts
- src/providers/ims-service.spec.ts
- src/providers/ims-service.ts
- src/providers/model-service.spec.ts
- src/providers/model-service.ts
> Model service to get metadata on image fields

- src/pages/entries/entries.ts
- src/pages/login/login.ts
- src/providers/loading-service.spec.ts
- src/providers/loading-service.ts
Refactoring for better reuse of code
> Refactor allow to wrap an observable execution with a loading dialog.

- src/pages/upload/upload.html
- src/pages/upload/upload.scss
- src/pages/upload/upload.spec.ts
- src/pages/upload/upload.ts
> Metadata fields

- README.md
> describe ionic view and clarify manual test cases

- docs/risikoanalyse.md
Marking Risk ID 5 as done. While we never got a formal approval on the specs from our stakeholders they did not give further input the general feeling is they are ok with it.
> Reflect current state of project in risk log

- docs/spec.md
New android version for samsung galaxy s7 has been released
> update reference device android version

- src/pages/upload/upload.ts
- src/providers/setting-service.ts
just two minor things I noticed from PR #289
> minor fixes: remove console.log, use fieldPathSeparator

- docs/spec.md
> Add language to priority matrix

- src/pages/entries/entries.html
- src/pages/entries/entries.ts
> Use click onstead of tab to open a popover.

- src/pages/setting-image-fields/setting-image-fields.html
- src/pages/setting-image-fields/setting-image-fields.spec.ts
- src/pages/setting-image-fields/setting-image-fields.ts
Can also be verified on ionic-lab
> Use ngFor on ion-item instead of ion-list to fix ios display problems

- src/pages/entries/entries.spec.ts
- src/pages/entries/entries.ts
- src/pages/upload/upload.ts
- src/providers/camera-service.spec.ts
- src/providers/camera-service.ts
The simplest possible implementation i could think of. Thanks for your input Sandro!
Closes #257
> Only show unexpected camera errors (no cancels and denied permission)

- README.md
- docs/glossary.md
- docs/spec.md
This should give us some words to use in future so our code and docs are more consistent.
Closes #156
> Improve glossary for constistency in wording

- package.json
> update ionic cli plugins to latest

- docs/spec.md
Modifiy NF13 after talking with stakeholder about expectation of NF13. This closes #319
> Specification of NF13

- README.md
- docs/spec.md
> Describe requirements for Developer documentation

- src/app/app.providers.ts
- src/mocks/ims-backend-mock.ts
- src/mocks/providers/auth-service-mock.ts
- src/mocks/providers/camera-mock.ts
- src/mocks/providers/setting-service-mock.ts
- src/mocks/providers/transfer-blob-mock.ts
- src/mocks/providers/transfer-mock.ts
- src/pages/entries/entries.spec.ts
- src/pages/login/login.spec.ts
- src/pages/setting-image-fields/setting-image-fields.spec.ts
- src/pages/upload/upload.spec.ts
- src/providers/auth-service.spec.ts
- src/providers/entries-service.spec.ts
- src/providers/ims-service.spec.ts
- src/providers/model-service.spec.ts
- src/providers/token-service.spec.ts
- src/providers/upload-service.spec.ts
> Refactor make mock classes name consistent

- src/app/app.module.ts
- src/pages/entries/entries.html
- src/pages/entries/entries.ts
- src/pages/login/login.html
- src/pages/login/login.ts
- src/pages/more-popover/more-popover.html
- src/pages/setting-image-fields/setting-image-fields.html
- src/pages/setting-image-fields/setting-image-fields.ts
- src/pages/settings/settings.html
- src/pages/upload/upload.html
- src/pages/upload/upload.ts
- src/providers/alert-service.ts
- src/providers/loading-service.ts
> Translate english ui components to german

- docs/decisionlog.md
New decisions from retro spective
> Add retro decisions

- README.md
Please don't forget to review the burnup chart itself 😄 
Closes #275
> Add burnup chart and reference in project plan

- e2e/upload.e2e-spec.ts
- src/providers/loading-service.spec.ts
- src/providers/loading-service.ts
> Bugfix loader

- README.md
closes #235 ( describe travis CI in proj plan )
> Travis ci documentation

- .travis.yml
- e2e/archive-selection.e2e-spec.ts
- e2e/entries.e2e-spec.ts
- e2e/helpers/helpers.ts
- e2e/login.e2e-spec.ts
- e2e/logout.e2e-spec.ts
- e2e/page-objects/entries-page-object.ts
- e2e/page-objects/login-page-object.ts
- e2e/page-objects/setting-archive-page-object.ts
- e2e/page-objects/setting-image-field-page-object.ts
- e2e/page-objects/settings-page-object.ts
- e2e/page-objects/upload-page-object.ts
- e2e/settings.e2e-spec.ts
- e2e/upload.e2e-spec.ts
- package.json
- protractor.conf.js
This closes #224 and closes  #333$
> E2e travis timing

- docs/protocols/2017-05-19-presentation-sprint6-imagic_PICSystem.md
closes #364 (sprint 6 protocol)
> Sprint 6 protocol

- docs/decisionlog.md
> Add decisions from sprint 7 retrospective

- scripts/run-ionic-cloud-builds-on-pr-or-master.sh
> ionic package in CI: use env variables for login

- e2e/page-objects/entries-page-object.ts
Faster travis execution with less waiting when entries page did load
> When loading entries page wait until ionView didEnter and didLoad

- e2e/login.e2e-spec.ts
- e2e/page-objects/login-page-object.ts
- src/providers/auth-service.ts
> Loading bug ios v2

- e2e/page-objects/upload-page-object.ts
- e2e/upload.e2e-spec.ts
- src/pages/upload/upload.html
- src/pages/upload/upload.scss
> visually mark mandatory fields on upload page

- e2e/page-objects/entries-page-object.ts
- e2e/page-objects/upload-page-object.ts
- e2e/upload.e2e-spec.ts
- src/mocks/providers/camera-mock.ts
- src/pages/entries/entries.html
- src/pages/entries/entries.spec.ts
- src/pages/entries/entries.ts
- src/pages/upload/upload.html
- src/pages/upload/upload.spec.ts
- src/pages/upload/upload.ts
- src/providers/camera-service.spec.ts
- src/providers/camera-service.ts
> Upload Single Image from Gallery

- README.md
> describe story map in project plan

- .travis.yml
- CONTRIBUTING.md
- README.md
- config.xml
- package.json
- scripts/version-consistency.sh
- src/pages/login/login.html
- src/pages/login/login.ts
> Semantic Versioning

- docs/protocols/2017-06-16-presentation-sprint8-imagic_PICSystem.md
Closes #396 (sprint 8 protocol)
> add protocol from sprint review 8

- e2e/archive-selection.e2e-spec.ts
- e2e/entries.e2e-spec.ts
- e2e/login.e2e-spec.ts
- e2e/logout.e2e-spec.ts
- e2e/page-objects/entries-page-object.ts
- e2e/page-objects/login-page-object.ts
- e2e/page-objects/setting-archive-page-object.ts
- e2e/page-objects/setting-entries-field-page-object.ts
- e2e/page-objects/setting-image-field-page-object.ts
- e2e/page-objects/settings-page-object.ts
- e2e/page-objects/upload-page-object.ts
- e2e/settings.e2e-spec.ts
- e2e/upload.e2e-spec.ts
> refactor: make e2e page object names consistent

- docs/protocols/2017-06-27-advisor-meeting.md
This documents our meeting on 2017-06-27.
> docs: add protocol of meeting with advisor

- scripts/release.js
Make releasing easier for reviewer with step by step guide on how to commit a release.
Closes #440
> build: pretty print release steps for release commit

- CONTRIBUTING.md
> docs: add release to allowed commit types

- tslint.json
- prefer-for-of
- unified-signatures
- no-duplicate-super
- arrow-return-shorthand
- no-object-literal-type-assertion
> build: add multiple lint rules

- e2e/archive-selection.e2e-spec.ts
- e2e/entries.e2e-spec.ts
- e2e/helpers/helpers.ts
- e2e/login.e2e-spec.ts
- e2e/logout.e2e-spec.ts
- e2e/page-objects/entries-page-object.ts
- e2e/settings.e2e-spec.ts
- e2e/upload.e2e-spec.ts
- src/components/ims-field-selection/ims-field-selection.spec.ts
- src/mocks/ims-backend-mock.ts
- src/models/drag-event-counter.spec.ts
- src/pages/login/login.ts
- src/pages/upload/upload.spec.ts
- src/providers/camera-service.ts
- src/providers/field-validator-service.spec.ts
- src/providers/ims-service.ts
- src/providers/loading-service.spec.ts
- src/providers/model-service.ts
- tslint.json
> build: add lint rule "no-magic-numbers"

- src/mocks/ims-backend-mock.ts
- tslint.json
Refactor ImsBackendMock with a url-like structure which needs to be generated on each request because some tests modify the response values.
> build: add lint rule "cyclomatic-complexity"

- docs/protocols/2017-07-14-presentation-sprint10-imagic_PICSystem.md
> docs: add protocol from sprint review 10

- src/app/app.component.spec.ts
- src/app/app.module.ts
- src/app/main.ts
- src/models/archive-table-entry.ts
- src/providers/ims-service.ts
The grouping did not convey any meaning anymore. Now all imports are consistently alphabetized.
> style: remove grouping of import sources

- docs/store.md
> docs: Add marketing text for app / play store 

- docs/abstract.md
For our project we have to deliver a short abstract of our work to HSR.
This closes #424
> docs: add abstract

- src/app/app.component.ts
- src/components/ims-field-selection/ims-field-selection.ts
- src/mocks/ims-backend-mock.ts
- src/mocks/providers/transfer-mock.ts
- src/mocks/response/error-response.ts
- src/models/errors/camera-error.ts
- src/models/errors/ims-authentication-error.ts
- src/models/errors/ims-error.ts
- src/models/errors/ims-loading-error.ts
- src/models/errors/ims-server-connection-error.ts
- src/models/errors/ims-upload-error.ts
- src/pages/entries/entries.ts
- src/pages/upload/upload.ts
- src/providers/browser-container-upload-service.ts
- src/providers/browser-fileupload-selector-service.ts
- src/providers/camera-service.ts
- src/providers/container-upload-service.ts
- src/providers/field-validator-service.ts
- src/providers/ims-error-handler.ts
- src/providers/loading-service.ts
- src/providers/setting-service.ts
- tslint.json
Lintrule "no-any" will be activated for all future releases. This should prevent new "any"-problems in the code.
Closes #492
> build: add lintrule "no-any"

- docs/sad.md
Add new folders, update description and change folder name style to kebab case, sort alphabetically.
> docs: update folder structure in sad

- docs/protocols/2017-07-28-presentation-sprint11-imagic_PICSystem.md
> docs: add protocol from sprintreview 11

- docs/abstract.md
Autocorrection has found two typos in our abstract.
> docs: fix typos in abstract

- docs/protocols/2017-08-11-presentation-sprint12-imagic_PICSystem.md
- docs/protokolle.md
> docs: add protocol from sprint review 12

- docs/sad.md
For a better understanding of our design principles and most important patterns, we created a design principles chapter in the software architecture document. It should help new developer to better understand the existing solution and motivate to develop in the same style.
closes #485
> docs: create chapter about our design principles

- docs/projektplan.md
> docs: extend documentation for e2e and manual testing

- docs/sad.md
- docs/spec.md
Add a introduction to the SAD which links the requirements to our architectural choices.
Closes #571
> docs: describe influence of requirements on the architecture

- docs/sad.md
Due to input from advisor we changed the order of chapters in the sad to have a more common structure.
Closes #556
> docs: reorganize sad according to common sad examples

- docs/projektplan.md
Show that we are all on the same level.
Closes #618
> docs: refactor authorship title and table

- docs/persoenlichesfazit.md
- docs/projektretro.md
- docs/protocols/2017-08-18-project-handover.md
- docs/sad.md
- docs/schnellstartanleitung.md
Corrections of the new texts in 25288bb...295c508.
Closes #628
> docs: fix typos discovered in second external review
